# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui_CellCount_18_MainWindow.ui'
#
# Created: Thu Aug 16 13:56:01 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(994, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(940, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/Start.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 951, 571))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(1000, 600))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_5)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setGeometry(QtCore.QRect(680, 370, 101, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 20, 631, 333))
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.grids = QtGui.QLabel(self.groupBox_8)
        self.grids.setGeometry(QtCore.QRect(297, 18, 300, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grids.sizePolicy().hasHeightForWidth())
        self.grids.setSizePolicy(sizePolicy)
        self.grids.setMinimumSize(QtCore.QSize(300, 300))
        self.grids.setMaximumSize(QtCore.QSize(300, 300))
        self.grids.setText(_fromUtf8(""))
        self.grids.setObjectName(_fromUtf8("grids"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_2.setGeometry(QtCore.QRect(28, 23, 250, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.platetype = QtGui.QComboBox(self.groupBox_2)
        self.platetype.setEditable(False)
        self.platetype.setMaxVisibleItems(5)
        self.platetype.setModelColumn(0)
        self.platetype.setObjectName(_fromUtf8("platetype"))
        self.horizontalLayout_2.addWidget(self.platetype)
        self.Group_subgrid = QtGui.QGroupBox(self.groupBox_8)
        self.Group_subgrid.setGeometry(QtCore.QRect(30, 80, 250, 200))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Group_subgrid.sizePolicy().hasHeightForWidth())
        self.Group_subgrid.setSizePolicy(sizePolicy)
        self.Group_subgrid.setMinimumSize(QtCore.QSize(250, 200))
        self.Group_subgrid.setMaximumSize(QtCore.QSize(200, 150))
        self.Group_subgrid.setCheckable(True)
        self.Group_subgrid.setChecked(False)
        self.Group_subgrid.setObjectName(_fromUtf8("Group_subgrid"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Group_subgrid)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.combo_decimation = QtGui.QComboBox(self.Group_subgrid)
        self.combo_decimation.setObjectName(_fromUtf8("combo_decimation"))
        self.combo_decimation.addItem(_fromUtf8(""))
        self.combo_decimation.addItem(_fromUtf8(""))
        self.combo_decimation.addItem(_fromUtf8(""))
        self.combo_decimation.addItem(_fromUtf8(""))
        self.combo_decimation.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.combo_decimation, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.Group_subgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(60, 0))
        self.label_15.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 2, 0, 1, 1)
        self.durationWell = QtGui.QLabel(self.Group_subgrid)
        self.durationWell.setText(_fromUtf8(""))
        self.durationWell.setObjectName(_fromUtf8("durationWell"))
        self.gridLayout_7.addWidget(self.durationWell, 4, 1, 1, 1)
        self.combo_cols = QtGui.QComboBox(self.Group_subgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_cols.sizePolicy().hasHeightForWidth())
        self.combo_cols.setSizePolicy(sizePolicy)
        self.combo_cols.setObjectName(_fromUtf8("combo_cols"))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.combo_cols.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.combo_cols, 1, 1, 1, 1)
        self.combo_rows = QtGui.QComboBox(self.Group_subgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_rows.sizePolicy().hasHeightForWidth())
        self.combo_rows.setSizePolicy(sizePolicy)
        self.combo_rows.setObjectName(_fromUtf8("combo_rows"))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.combo_rows.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.combo_rows, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.Group_subgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(60, 0))
        self.label_14.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.Group_subgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(60, 0))
        self.label_16.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.Group_subgrid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMaximumSize(QtCore.QSize(70, 20))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_7.addWidget(self.label_36, 0, 0, 1, 1)
        self.sliderRadial = QtGui.QSlider(self.Group_subgrid)
        self.sliderRadial.setMinimum(1)
        self.sliderRadial.setMaximum(5)
        self.sliderRadial.setPageStep(1)
        self.sliderRadial.setOrientation(QtCore.Qt.Horizontal)
        self.sliderRadial.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderRadial.setTickInterval(1)
        self.sliderRadial.setObjectName(_fromUtf8("sliderRadial"))
        self.gridLayout_7.addWidget(self.sliderRadial, 0, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.Group_subgrid)
        self.label_35.setMinimumSize(QtCore.QSize(60, 25))
        self.label_35.setMaximumSize(QtCore.QSize(70, 25))
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_7.addWidget(self.label_35, 4, 0, 1, 1)
        self.buttonSaveParams = QtGui.QPushButton(self.groupBox_8)
        self.buttonSaveParams.setGeometry(QtCore.QRect(110, 280, 75, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSaveParams.sizePolicy().hasHeightForWidth())
        self.buttonSaveParams.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonSaveParams.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/plate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSaveParams.setIcon(icon1)
        self.buttonSaveParams.setObjectName(_fromUtf8("buttonSaveParams"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 360, 641, 91))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setMargin(2)
        self.gridLayout_9.setHorizontalSpacing(4)
        self.gridLayout_9.setVerticalSpacing(2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lineRecep3 = QtGui.QLineEdit(self.groupBox_9)
        self.lineRecep3.setObjectName(_fromUtf8("lineRecep3"))
        self.gridLayout_9.addWidget(self.lineRecep3, 2, 3, 1, 1)
        self.lineRecep2 = QtGui.QLineEdit(self.groupBox_9)
        self.lineRecep2.setObjectName(_fromUtf8("lineRecep2"))
        self.gridLayout_9.addWidget(self.lineRecep2, 1, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_9)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 2, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_9)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_9.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_9)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_9.addWidget(self.label_23, 2, 0, 1, 1)
        self.linePass = QtGui.QLineEdit(self.groupBox_9)
        self.linePass.setEchoMode(QtGui.QLineEdit.Password)
        self.linePass.setObjectName(_fromUtf8("linePass"))
        self.gridLayout_9.addWidget(self.linePass, 1, 1, 1, 1)
        self.lineRecep1 = QtGui.QLineEdit(self.groupBox_9)
        self.lineRecep1.setObjectName(_fromUtf8("lineRecep1"))
        self.gridLayout_9.addWidget(self.lineRecep1, 0, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_9)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 1, 0, 1, 1)
        self.buttonMailtest = QtGui.QPushButton(self.groupBox_9)
        self.buttonMailtest.setMaximumSize(QtCore.QSize(50, 50))
        self.buttonMailtest.setObjectName(_fromUtf8("buttonMailtest"))
        self.gridLayout_9.addWidget(self.buttonMailtest, 1, 4, 1, 1)
        self.lineSMTP = QtGui.QLineEdit(self.groupBox_9)
        self.lineSMTP.setObjectName(_fromUtf8("lineSMTP"))
        self.gridLayout_9.addWidget(self.lineSMTP, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_9)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 1, 2, 1, 1)
        self.lineSender = QtGui.QLineEdit(self.groupBox_9)
        self.lineSender.setObjectName(_fromUtf8("lineSender"))
        self.gridLayout_9.addWidget(self.lineSender, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_9)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 0, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(670, 20, 230, 330))
        self.groupBox_10.setMinimumSize(QtCore.QSize(230, 330))
        self.groupBox_10.setMaximumSize(QtCore.QSize(230, 330))
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_27 = QtGui.QLabel(self.groupBox_10)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.labelBCKGND = QtGui.QLabel(self.groupBox_10)
        self.labelBCKGND.setMinimumSize(QtCore.QSize(192, 108))
        self.labelBCKGND.setMaximumSize(QtCore.QSize(192, 108))
        self.labelBCKGND.setToolTip(_fromUtf8(""))
        self.labelBCKGND.setText(_fromUtf8(""))
        self.labelBCKGND.setObjectName(_fromUtf8("labelBCKGND"))
        self.verticalLayout.addWidget(self.labelBCKGND)
        self.pushButtonBCKGND = QtGui.QPushButton(self.groupBox_10)
        self.pushButtonBCKGND.setObjectName(_fromUtf8("pushButtonBCKGND"))
        self.verticalLayout.addWidget(self.pushButtonBCKGND)
        self.pushButtonBCKGND2 = QtGui.QPushButton(self.groupBox_10)
        self.pushButtonBCKGND2.setObjectName(_fromUtf8("pushButtonBCKGND2"))
        self.verticalLayout.addWidget(self.pushButtonBCKGND2)
        self.labelLOGO = QtGui.QLabel(self.tab_5)
        self.labelLOGO.setGeometry(QtCore.QRect(800, 360, 80, 70))
        self.labelLOGO.setText(_fromUtf8(""))
        self.labelLOGO.setTextFormat(QtCore.Qt.RichText)
        self.labelLOGO.setPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/Logo.png")))
        self.labelLOGO.setScaledContents(True)
        self.labelLOGO.setObjectName(_fromUtf8("labelLOGO"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 591, 391))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox.setFont(font)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(600, 329, 321, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.dial_duration = QtGui.QDial(self.groupBox_3)
        self.dial_duration.setGeometry(QtCore.QRect(0, 70, 121, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_duration.sizePolicy().hasHeightForWidth())
        self.dial_duration.setSizePolicy(sizePolicy)
        self.dial_duration.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dial_duration.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_duration.setMinimum(1)
        self.dial_duration.setMaximum(72)
        self.dial_duration.setSingleStep(1)
        self.dial_duration.setProperty("value", 1)
        self.dial_duration.setTracking(True)
        self.dial_duration.setOrientation(QtCore.Qt.Horizontal)
        self.dial_duration.setInvertedAppearance(False)
        self.dial_duration.setInvertedControls(False)
        self.dial_duration.setObjectName(_fromUtf8("dial_duration"))
        self.label_duration = QtGui.QLabel(self.groupBox_3)
        self.label_duration.setGeometry(QtCore.QRect(50, 50, 41, 28))
        self.label_duration.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_duration.setFont(font)
        self.label_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_duration.setWordWrap(False)
        self.label_duration.setObjectName(_fromUtf8("label_duration"))
        self.label_repeats = QtGui.QLabel(self.groupBox_3)
        self.label_repeats.setGeometry(QtCore.QRect(118, 155, 41, 28))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_repeats.setFont(font)
        self.label_repeats.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_repeats.setWordWrap(False)
        self.label_repeats.setObjectName(_fromUtf8("label_repeats"))
        self.dial_period = QtGui.QDial(self.groupBox_3)
        self.dial_period.setGeometry(QtCore.QRect(165, 70, 121, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_period.sizePolicy().hasHeightForWidth())
        self.dial_period.setSizePolicy(sizePolicy)
        self.dial_period.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dial_period.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dial_period.setMinimum(15)
        self.dial_period.setMaximum(120)
        self.dial_period.setSingleStep(15)
        self.dial_period.setInvertedAppearance(False)
        self.dial_period.setInvertedControls(False)
        self.dial_period.setObjectName(_fromUtf8("dial_period"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(117, 138, 48, 16))
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(142, 23, 171, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setWordWrap(False)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_period = QtGui.QLabel(self.groupBox_3)
        self.label_period.setGeometry(QtCore.QRect(200, 50, 41, 28))
        self.label_period.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_period.setFont(font)
        self.label_period.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_period.setWordWrap(False)
        self.label_period.setObjectName(_fromUtf8("label_period"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(13, 21, 111, 16))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setWordWrap(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(138, 30, 2, 60))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(600, 20, 321, 301))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 294, 201))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineWP1 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWP1.sizePolicy().hasHeightForWidth())
        self.lineWP1.setSizePolicy(sizePolicy)
        self.lineWP1.setMaxLength(24)
        self.lineWP1.setObjectName(_fromUtf8("lineWP1"))
        self.gridLayout_4.addWidget(self.lineWP1, 2, 1, 1, 1)
        self.lineWP2 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWP2.sizePolicy().hasHeightForWidth())
        self.lineWP2.setSizePolicy(sizePolicy)
        self.lineWP2.setMaxLength(24)
        self.lineWP2.setObjectName(_fromUtf8("lineWP2"))
        self.gridLayout_4.addWidget(self.lineWP2, 4, 1, 1, 1)
        self.lineWP0 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWP0.sizePolicy().hasHeightForWidth())
        self.lineWP0.setSizePolicy(sizePolicy)
        self.lineWP0.setMaxLength(24)
        self.lineWP0.setReadOnly(True)
        self.lineWP0.setObjectName(_fromUtf8("lineWP0"))
        self.gridLayout_4.addWidget(self.lineWP0, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 5, 0, 1, 1)
        self.lineWP3 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWP3.sizePolicy().hasHeightForWidth())
        self.lineWP3.setSizePolicy(sizePolicy)
        self.lineWP3.setMaxLength(24)
        self.lineWP3.setObjectName(_fromUtf8("lineWP3"))
        self.gridLayout_4.addWidget(self.lineWP3, 5, 1, 1, 1)
        self.lineWP4 = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWP4.sizePolicy().hasHeightForWidth())
        self.lineWP4.setSizePolicy(sizePolicy)
        self.lineWP4.setMaxLength(24)
        self.lineWP4.setObjectName(_fromUtf8("lineWP4"))
        self.gridLayout_4.addWidget(self.lineWP4, 6, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.unitsCompound = QtGui.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unitsCompound.sizePolicy().hasHeightForWidth())
        self.unitsCompound.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unitsCompound.setFont(font)
        self.unitsCompound.setStatusTip(_fromUtf8(""))
        self.unitsCompound.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.unitsCompound.setObjectName(_fromUtf8("unitsCompound"))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.unitsCompound.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.unitsCompound, 6, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 270, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_9.setGeometry(QtCore.QRect(150, 270, 75, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 410, 201, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_HALT = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_HALT.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_HALT.setFont(font)
        self.pushButton_HALT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/stop.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_HALT.setIcon(icon2)
        self.pushButton_HALT.setObjectName(_fromUtf8("pushButton_HALT"))
        self.horizontalLayout.addWidget(self.pushButton_HALT)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 468, 541, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.progressPlate = QtGui.QProgressBar(self.groupBox_5)
        self.progressPlate.setGeometry(QtCore.QRect(60, 30, 200, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.progressPlate.setFont(font)
        self.progressPlate.setMaximum(1)
        self.progressPlate.setProperty("value", 0)
        self.progressPlate.setOrientation(QtCore.Qt.Horizontal)
        self.progressPlate.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressPlate.setObjectName(_fromUtf8("progressPlate"))
        self.progressParadigm = QtGui.QProgressBar(self.groupBox_5)
        self.progressParadigm.setGeometry(QtCore.QRect(340, 30, 200, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.progressParadigm.setFont(font)
        self.progressParadigm.setMaximum(1)
        self.progressParadigm.setProperty("value", 0)
        self.progressParadigm.setTextVisible(True)
        self.progressParadigm.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressParadigm.setObjectName(_fromUtf8("progressParadigm"))
        self.countStatus = QtGui.QLabel(self.groupBox_5)
        self.countStatus.setGeometry(QtCore.QRect(10, 60, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.countStatus.setFont(font)
        self.countStatus.setText(_fromUtf8(""))
        self.countStatus.setTextFormat(QtCore.Qt.PlainText)
        self.countStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.countStatus.setObjectName(_fromUtf8("countStatus"))
        self.label_39 = QtGui.QLabel(self.groupBox_5)
        self.label_39.setGeometry(QtCore.QRect(10, 30, 48, 16))
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setWordWrap(False)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.groupBox_5)
        self.label_40.setGeometry(QtCore.QRect(290, 30, 48, 16))
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setWordWrap(False)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(61, 607, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.status2 = QtGui.QLabel(self.tab_2)
        self.status2.setGeometry(QtCore.QRect(700, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("HP Simplified"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.status2.setFont(font)
        self.status2.setTextFormat(QtCore.Qt.PlainText)
        self.status2.setAlignment(QtCore.Qt.AlignCenter)
        self.status2.setObjectName(_fromUtf8("status2"))
        self.pixel_val = QtGui.QLabel(self.tab_2)
        self.pixel_val.setGeometry(QtCore.QRect(40, 10, 241, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("HP Simplified"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pixel_val.setFont(font)
        self.pixel_val.setTextFormat(QtCore.Qt.PlainText)
        self.pixel_val.setObjectName(_fromUtf8("pixel_val"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 640, 360))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(1)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.buttonStartLive = QtGui.QPushButton(self.tab_2)
        self.buttonStartLive.setGeometry(QtCore.QRect(700, 40, 75, 23))
        self.buttonStartLive.setObjectName(_fromUtf8("buttonStartLive"))
        self.buttonStopLive = QtGui.QPushButton(self.tab_2)
        self.buttonStopLive.setGeometry(QtCore.QRect(780, 40, 75, 23))
        self.buttonStopLive.setObjectName(_fromUtf8("buttonStopLive"))
        self.groupBox_Focus = QtGui.QGroupBox(self.tab_2)
        self.groupBox_Focus.setGeometry(QtCore.QRect(40, 390, 421, 118))
        self.groupBox_Focus.setObjectName(_fromUtf8("groupBox_Focus"))
        self.sliderFocuserCoarse = QtGui.QSlider(self.groupBox_Focus)
        self.sliderFocuserCoarse.setGeometry(QtCore.QRect(70, 10, 341, 31))
        self.sliderFocuserCoarse.setMinimumSize(QtCore.QSize(250, 0))
        self.sliderFocuserCoarse.setMinimum(1)
        self.sliderFocuserCoarse.setMaximum(20)
        self.sliderFocuserCoarse.setPageStep(2)
        self.sliderFocuserCoarse.setProperty("value", 10)
        self.sliderFocuserCoarse.setTracking(False)
        self.sliderFocuserCoarse.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFocuserCoarse.setInvertedAppearance(False)
        self.sliderFocuserCoarse.setInvertedControls(False)
        self.sliderFocuserCoarse.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderFocuserCoarse.setTickInterval(1)
        self.sliderFocuserCoarse.setObjectName(_fromUtf8("sliderFocuserCoarse"))
        self.sliderFocuserFine = QtGui.QSlider(self.groupBox_Focus)
        self.sliderFocuserFine.setGeometry(QtCore.QRect(70, 40, 341, 20))
        self.sliderFocuserFine.setMinimum(1)
        self.sliderFocuserFine.setMaximum(16)
        self.sliderFocuserFine.setPageStep(4)
        self.sliderFocuserFine.setProperty("value", 8)
        self.sliderFocuserFine.setSliderPosition(8)
        self.sliderFocuserFine.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFocuserFine.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderFocuserFine.setTickInterval(1)
        self.sliderFocuserFine.setObjectName(_fromUtf8("sliderFocuserFine"))
        self.label_37 = QtGui.QLabel(self.groupBox_Focus)
        self.label_37.setGeometry(QtCore.QRect(10, 20, 42, 16))
        self.label_37.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox_Focus)
        self.label_38.setGeometry(QtCore.QRect(20, 40, 30, 16))
        self.label_38.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.buttonLensReset = QtGui.QPushButton(self.groupBox_Focus)
        self.buttonLensReset.setGeometry(QtCore.QRect(180, 70, 98, 23))
        self.buttonLensReset.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonLensReset.setObjectName(_fromUtf8("buttonLensReset"))
        self.buttonLensSavePosition = QtGui.QPushButton(self.groupBox_Focus)
        self.buttonLensSavePosition.setGeometry(QtCore.QRect(10, 90, 90, 23))
        self.buttonLensSavePosition.setMinimumSize(QtCore.QSize(90, 0))
        self.buttonLensSavePosition.setMaximumSize(QtCore.QSize(90, 16777215))
        self.buttonLensSavePosition.setObjectName(_fromUtf8("buttonLensSavePosition"))
        self.buttonLensSetOrigin = QtGui.QPushButton(self.groupBox_Focus)
        self.buttonLensSetOrigin.setGeometry(QtCore.QRect(10, 70, 90, 23))
        self.buttonLensSetOrigin.setMaximumSize(QtCore.QSize(90, 16777215))
        self.buttonLensSetOrigin.setObjectName(_fromUtf8("buttonLensSetOrigin"))
        self.groupBox_Navigator = QtGui.QGroupBox(self.tab_2)
        self.groupBox_Navigator.setGeometry(QtCore.QRect(470, 390, 201, 121))
        self.groupBox_Navigator.setObjectName(_fromUtf8("groupBox_Navigator"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_Navigator)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 111, 91))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.buttonYp = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonYp.sizePolicy().hasHeightForWidth())
        self.buttonYp.setSizePolicy(sizePolicy)
        self.buttonYp.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/moveYp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonYp.setIcon(icon3)
        self.buttonYp.setObjectName(_fromUtf8("buttonYp"))
        self.gridLayout_5.addWidget(self.buttonYp, 1, 2, 1, 1)
        self.buttonXp = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonXp.sizePolicy().hasHeightForWidth())
        self.buttonXp.setSizePolicy(sizePolicy)
        self.buttonXp.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/moveXp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonXp.setIcon(icon4)
        self.buttonXp.setObjectName(_fromUtf8("buttonXp"))
        self.gridLayout_5.addWidget(self.buttonXp, 2, 1, 1, 1)
        self.buttonYn = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonYn.sizePolicy().hasHeightForWidth())
        self.buttonYn.setSizePolicy(sizePolicy)
        self.buttonYn.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/moveYn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonYn.setIcon(icon5)
        self.buttonYn.setObjectName(_fromUtf8("buttonYn"))
        self.gridLayout_5.addWidget(self.buttonYn, 1, 0, 1, 1)
        self.buttonXn = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonXn.sizePolicy().hasHeightForWidth())
        self.buttonXn.setSizePolicy(sizePolicy)
        self.buttonXn.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/images/moveXn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonXn.setIcon(icon6)
        self.buttonXn.setObjectName(_fromUtf8("buttonXn"))
        self.gridLayout_5.addWidget(self.buttonXn, 0, 1, 1, 1)
        self.comboLive = QtGui.QComboBox(self.groupBox_Navigator)
        self.comboLive.setGeometry(QtCore.QRect(130, 20, 60, 21))
        self.comboLive.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboLive.setObjectName(_fromUtf8("comboLive"))
        self.buttonGo = QtGui.QPushButton(self.groupBox_Navigator)
        self.buttonGo.setGeometry(QtCore.QRect(130, 50, 60, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGo.sizePolicy().hasHeightForWidth())
        self.buttonGo.setSizePolicy(sizePolicy)
        self.buttonGo.setMaximumSize(QtCore.QSize(60, 16777215))
        self.buttonGo.setObjectName(_fromUtf8("buttonGo"))
        self.groupBox_CamParam = QtGui.QGroupBox(self.tab_2)
        self.groupBox_CamParam.setGeometry(QtCore.QRect(700, 70, 181, 481))
        self.groupBox_CamParam.setObjectName(_fromUtf8("groupBox_CamParam"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_CamParam)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 161, 395))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(2, -1, 2, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalSlider = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider.setMinimum(-63)
        self.verticalSlider.setMaximum(63)
        self.verticalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider.setTickInterval(32)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.verticalLayout_2.addWidget(self.verticalSlider)
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalSlider_2 = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider_2.setMinimum(-64)
        self.verticalSlider_2.setMaximum(64)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_2.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider_2.setTickInterval(32)
        self.verticalSlider_2.setObjectName(_fromUtf8("verticalSlider_2"))
        self.verticalLayout_2.addWidget(self.verticalSlider_2)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalSlider_3 = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider_3.setMinimum(0)
        self.verticalSlider_3.setMaximum(100)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_3.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider_3.setTickInterval(32)
        self.verticalSlider_3.setObjectName(_fromUtf8("verticalSlider_3"))
        self.verticalLayout_2.addWidget(self.verticalSlider_3)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalSlider_4 = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider_4.setMinimum(-10)
        self.verticalSlider_4.setMaximum(-1)
        self.verticalSlider_4.setTracking(True)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_4.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider_4.setTickInterval(2)
        self.verticalSlider_4.setObjectName(_fromUtf8("verticalSlider_4"))
        self.verticalLayout_2.addWidget(self.verticalSlider_4)
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.verticalSlider_5 = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider_5.setMinimum(-2000)
        self.verticalSlider_5.setMaximum(2000)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_5.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider_5.setTickInterval(500)
        self.verticalSlider_5.setObjectName(_fromUtf8("verticalSlider_5"))
        self.verticalLayout_2.addWidget(self.verticalSlider_5)
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.verticalSlider_6 = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider_6.setMinimum(1)
        self.verticalSlider_6.setMaximum(100)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_6.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider_6.setTickInterval(10)
        self.verticalSlider_6.setObjectName(_fromUtf8("verticalSlider_6"))
        self.verticalLayout_2.addWidget(self.verticalSlider_6)
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.verticalSlider_7 = QtGui.QSlider(self.layoutWidget2)
        self.verticalSlider_7.setMinimum(1)
        self.verticalSlider_7.setMaximum(7)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSlider_7.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.verticalSlider_7.setTickInterval(1)
        self.verticalSlider_7.setObjectName(_fromUtf8("verticalSlider_7"))
        self.verticalLayout_2.addWidget(self.verticalSlider_7)
        self.buttonSnapshot = QtGui.QPushButton(self.groupBox_CamParam)
        self.buttonSnapshot.setEnabled(False)
        self.buttonSnapshot.setGeometry(QtCore.QRect(40, 430, 101, 21))
        self.buttonSnapshot.setObjectName(_fromUtf8("buttonSnapshot"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_CamParam)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 420, 16, 16))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.folderView = QtGui.QTreeView(self.tab_3)
        self.folderView.setGeometry(QtCore.QRect(1, 188, 191, 341))
        self.folderView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.folderView.setFrameShadow(QtGui.QFrame.Sunken)
        self.folderView.setLineWidth(2)
        self.folderView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.folderView.setTabKeyNavigation(True)
        self.folderView.setAlternatingRowColors(True)
        self.folderView.setTextElideMode(QtCore.Qt.ElideLeft)
        self.folderView.setRootIsDecorated(False)
        self.folderView.setUniformRowHeights(True)
        self.folderView.setItemsExpandable(False)
        self.folderView.setObjectName(_fromUtf8("folderView"))
        self.folderView.header().setCascadingSectionResizes(False)
        self.folderView.header().setDefaultSectionSize(170)
        self.folderView.header().setHighlightSections(True)
        self.folderView.header().setMinimumSectionSize(170)
        self.folderView.header().setSortIndicatorShown(True)
        self.folderView.header().setStretchLastSection(False)
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(5, 171, 61, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.pngList = QtGui.QListWidget(self.tab_3)
        self.pngList.setGeometry(QtCore.QRect(201, 188, 41, 341))
        self.pngList.setObjectName(_fromUtf8("pngList"))
        self.pngViewer = QtGui.QLabel(self.tab_3)
        self.pngViewer.setGeometry(QtCore.QRect(260, 20, 651, 501))
        self.pngViewer.setAlignment(QtCore.Qt.AlignCenter)
        self.pngViewer.setObjectName(_fromUtf8("pngViewer"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 10, 217, 151))
        self.groupBox_13.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_33 = QtGui.QLabel(self.groupBox_13)
        self.label_33.setMinimumSize(QtCore.QSize(75, 15))
        self.label_33.setMaximumSize(QtCore.QSize(75, 15))
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 4, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_13)
        self.label_29.setMinimumSize(QtCore.QSize(75, 15))
        self.label_29.setMaximumSize(QtCore.QSize(75, 15))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 3, 0, 1, 1)
        self.label_pngCycle = QtGui.QLabel(self.groupBox_13)
        self.label_pngCycle.setText(_fromUtf8(""))
        self.label_pngCycle.setObjectName(_fromUtf8("label_pngCycle"))
        self.gridLayout_2.addWidget(self.label_pngCycle, 4, 1, 1, 1)
        self.labelPNG_CompConc = QtGui.QLabel(self.groupBox_13)
        self.labelPNG_CompConc.setText(_fromUtf8(""))
        self.labelPNG_CompConc.setObjectName(_fromUtf8("labelPNG_CompConc"))
        self.gridLayout_2.addWidget(self.labelPNG_CompConc, 3, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(75, 15))
        self.label_34.setMaximumSize(QtCore.QSize(75, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 2, 0, 1, 1)
        self.labelPNG_Cell = QtGui.QLabel(self.groupBox_13)
        self.labelPNG_Cell.setObjectName(_fromUtf8("labelPNG_Cell"))
        self.gridLayout_2.addWidget(self.labelPNG_Cell, 1, 1, 1, 1)
        self.labelPNG_Well = QtGui.QLabel(self.groupBox_13)
        self.labelPNG_Well.setObjectName(_fromUtf8("labelPNG_Well"))
        self.gridLayout_2.addWidget(self.labelPNG_Well, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(75, 15))
        self.label_31.setMaximumSize(QtCore.QSize(75, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 0, 0, 1, 1)
        self.labelPNG_Compund = QtGui.QLabel(self.groupBox_13)
        self.labelPNG_Compund.setObjectName(_fromUtf8("labelPNG_Compund"))
        self.gridLayout_2.addWidget(self.labelPNG_Compund, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(75, 15))
        self.label_32.setMaximumSize(QtCore.QSize(75, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 1, 0, 1, 1)
        self.pngCycle = QtGui.QSlider(self.groupBox_13)
        self.pngCycle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pngCycle.setMinimum(1)
        self.pngCycle.setMaximum(2)
        self.pngCycle.setPageStep(1)
        self.pngCycle.setOrientation(QtCore.Qt.Horizontal)
        self.pngCycle.setInvertedAppearance(False)
        self.pngCycle.setInvertedControls(False)
        self.pngCycle.setTickPosition(QtGui.QSlider.TicksAbove)
        self.pngCycle.setTickInterval(1)
        self.pngCycle.setObjectName(_fromUtf8("pngCycle"))
        self.gridLayout_2.addWidget(self.pngCycle, 6, 0, 1, 2)
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(205, 171, 46, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 731, 501))
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.logger = QtGui.QListWidget(self.groupBox_4)
        self.logger.setGeometry(QtCore.QRect(10, 20, 711, 471))
        self.logger.setObjectName(_fromUtf8("logger"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.platetype.setCurrentIndex(-1)
        self.unitsCompound.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.groupBox_3)
        MainWindow.setTabOrder(self.groupBox_3, self.dial_duration)
        MainWindow.setTabOrder(self.dial_duration, self.dial_period)
        MainWindow.setTabOrder(self.dial_period, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_HALT)
        MainWindow.setTabOrder(self.pushButton_HALT, self.lineWP0)
        MainWindow.setTabOrder(self.lineWP0, self.lineWP1)
        MainWindow.setTabOrder(self.lineWP1, self.lineWP2)
        MainWindow.setTabOrder(self.lineWP2, self.lineWP3)
        MainWindow.setTabOrder(self.lineWP3, self.lineWP4)
        MainWindow.setTabOrder(self.lineWP4, self.buttonSnapshot)
        MainWindow.setTabOrder(self.buttonSnapshot, self.comboLive)
        MainWindow.setTabOrder(self.comboLive, self.verticalSlider)
        MainWindow.setTabOrder(self.verticalSlider, self.verticalSlider_2)
        MainWindow.setTabOrder(self.verticalSlider_2, self.verticalSlider_3)
        MainWindow.setTabOrder(self.verticalSlider_3, self.verticalSlider_4)
        MainWindow.setTabOrder(self.verticalSlider_4, self.verticalSlider_5)
        MainWindow.setTabOrder(self.verticalSlider_5, self.verticalSlider_6)
        MainWindow.setTabOrder(self.verticalSlider_6, self.verticalSlider_7)
        MainWindow.setTabOrder(self.verticalSlider_7, self.buttonStartLive)
        MainWindow.setTabOrder(self.buttonStartLive, self.buttonStopLive)
        MainWindow.setTabOrder(self.buttonStopLive, self.comboBox_3)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Incu-Scope", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Plate Type / Acquisition", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Plate Type", None))
        self.Group_subgrid.setTitle(_translate("MainWindow", "Subgrid Capturing", None))
        self.combo_decimation.setToolTip(_translate("MainWindow", "Set low values for smaller image", None))
        self.combo_decimation.setItemText(0, _translate("MainWindow", "1.00  (1920 x 1080)", None))
        self.combo_decimation.setItemText(1, _translate("MainWindow", "0.75  (1440 x 810)", None))
        self.combo_decimation.setItemText(2, _translate("MainWindow", "0.50   (960 x 540)", None))
        self.combo_decimation.setItemText(3, _translate("MainWindow", "0.25   (480 x 270)", None))
        self.combo_decimation.setItemText(4, _translate("MainWindow", "0.10   (192 x 108)", None))
        self.label_15.setText(_translate("MainWindow", "Rows:", None))
        self.combo_cols.setItemText(0, _translate("MainWindow", "01", None))
        self.combo_cols.setItemText(1, _translate("MainWindow", "03", None))
        self.combo_cols.setItemText(2, _translate("MainWindow", "05", None))
        self.combo_cols.setItemText(3, _translate("MainWindow", "07", None))
        self.combo_cols.setItemText(4, _translate("MainWindow", "09", None))
        self.combo_cols.setItemText(5, _translate("MainWindow", "11", None))
        self.combo_cols.setItemText(6, _translate("MainWindow", "13", None))
        self.combo_cols.setItemText(7, _translate("MainWindow", "15", None))
        self.combo_cols.setItemText(8, _translate("MainWindow", "17", None))
        self.combo_cols.setItemText(9, _translate("MainWindow", "19", None))
        self.combo_cols.setItemText(10, _translate("MainWindow", "21", None))
        self.combo_cols.setItemText(11, _translate("MainWindow", "23", None))
        self.combo_cols.setItemText(12, _translate("MainWindow", "25", None))
        self.combo_rows.setItemText(0, _translate("MainWindow", "01", None))
        self.combo_rows.setItemText(1, _translate("MainWindow", "03", None))
        self.combo_rows.setItemText(2, _translate("MainWindow", "05", None))
        self.combo_rows.setItemText(3, _translate("MainWindow", "07", None))
        self.combo_rows.setItemText(4, _translate("MainWindow", "09", None))
        self.combo_rows.setItemText(5, _translate("MainWindow", "11", None))
        self.combo_rows.setItemText(6, _translate("MainWindow", "13", None))
        self.combo_rows.setItemText(7, _translate("MainWindow", "15", None))
        self.combo_rows.setItemText(8, _translate("MainWindow", "17", None))
        self.combo_rows.setItemText(9, _translate("MainWindow", "19", None))
        self.combo_rows.setItemText(10, _translate("MainWindow", "21", None))
        self.combo_rows.setItemText(11, _translate("MainWindow", "23", None))
        self.combo_rows.setItemText(12, _translate("MainWindow", "25", None))
        self.label_14.setText(_translate("MainWindow", "Columns:", None))
        self.label_16.setText(_translate("MainWindow", "Decimation:", None))
        self.label_36.setText(_translate("MainWindow", "Radial:", None))
        self.label_35.setText(_translate("MainWindow", "Dur./well :", None))
        self.buttonSaveParams.setText(_translate("MainWindow", "Save", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Get status via e-mail", None))
        self.label_26.setText(_translate("MainWindow", "Receipient 3:", None))
        self.label_24.setText(_translate("MainWindow", "Receipient 1:", None))
        self.label_23.setText(_translate("MainWindow", "SMTP:", None))
        self.label_22.setText(_translate("MainWindow", "Password:", None))
        self.buttonMailtest.setText(_translate("MainWindow", "Test", None))
        self.label_25.setText(_translate("MainWindow", "Receipient 2:", None))
        self.label_21.setText(_translate("MainWindow", "Sender:", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Background Correction", None))
        self.label_27.setText(_translate("MainWindow", "Current:", None))
        self.pushButtonBCKGND.setToolTip(_translate("MainWindow", "Updates background image for proper acquisition", None))
        self.pushButtonBCKGND.setText(_translate("MainWindow", "Update via Camera", None))
        self.pushButtonBCKGND2.setText(_translate("MainWindow", "Update via File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Setup", None))
        self.groupBox.setTitle(_translate("MainWindow", "Plate Layout", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Time Lapse Acquisition", None))
        self.label_duration.setText(_translate("MainWindow", "999", None))
        self.label_repeats.setText(_translate("MainWindow", "999", None))
        self.label_20.setText(_translate("MainWindow", "Repeats:", None))
        self.label_18.setText(_translate("MainWindow", "Repeat Period (Minutes):", None))
        self.label_period.setText(_translate("MainWindow", "999", None))
        self.label_19.setText(_translate("MainWindow", "Duration (Hours): ", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Well Properties", None))
        self.label_8.setText(_translate("MainWindow", "Cell Count:", None))
        self.label_9.setText(_translate("MainWindow", "Compund Name:", None))
        self.label.setText(_translate("MainWindow", "Well: ", None))
        self.label_10.setText(_translate("MainWindow", "Concentration:", None))
        self.label_7.setText(_translate("MainWindow", "Cell Name:", None))
        self.unitsCompound.setItemText(0, _translate("MainWindow", "mM", None))
        self.unitsCompound.setItemText(1, _translate("MainWindow", "uM", None))
        self.unitsCompound.setItemText(2, _translate("MainWindow", "nM", None))
        self.unitsCompound.setItemText(3, _translate("MainWindow", "pM", None))
        self.unitsCompound.setItemText(4, _translate("MainWindow", "fM", None))
        self.unitsCompound.setItemText(5, _translate("MainWindow", "mg/ml", None))
        self.unitsCompound.setItemText(6, _translate("MainWindow", "ug/ml", None))
        self.unitsCompound.setItemText(7, _translate("MainWindow", "ng/ml", None))
        self.unitsCompound.setItemText(8, _translate("MainWindow", "pg/ml", None))
        self.unitsCompound.setItemText(9, _translate("MainWindow", "%", None))
        self.unitsCompound.setItemText(10, _translate("MainWindow", "ppt", None))
        self.unitsCompound.setItemText(11, _translate("MainWindow", "ppm", None))
        self.unitsCompound.setItemText(12, _translate("MainWindow", "ppq", None))
        self.pushButton_8.setText(_translate("MainWindow", "Save", None))
        self.pushButton_9.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_2.setText(_translate("MainWindow", "Start", None))
        self.pushButton_HALT.setText(_translate("MainWindow", "Cancel", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Progress", None))
        self.progressPlate.setFormat(_translate("MainWindow", "%p%", None))
        self.progressParadigm.setFormat(_translate("MainWindow", "%p%", None))
        self.label_39.setText(_translate("MainWindow", "Overall:", None))
        self.label_40.setText(_translate("MainWindow", "Current:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Acquisition", None))
        self.label_17.setText(_translate("MainWindow", "Status:", None))
        self.status2.setText(_translate("MainWindow", "Live Mode OFF", None))
        self.pixel_val.setText(_translate("MainWindow", "(,)", None))
        self.label_2.setText(_translate("MainWindow", "Camera OFF", None))
        self.buttonStartLive.setText(_translate("MainWindow", "Start", None))
        self.buttonStopLive.setText(_translate("MainWindow", "Stop", None))
        self.groupBox_Focus.setTitle(_translate("MainWindow", "Focus", None))
        self.label_37.setText(_translate("MainWindow", "Coarse:", None))
        self.label_38.setText(_translate("MainWindow", "Fine:", None))
        self.buttonLensReset.setText(_translate("MainWindow", "Reset to Origin", None))
        self.buttonLensSavePosition.setText(_translate("MainWindow", "Memo", None))
        self.buttonLensSetOrigin.setText(_translate("MainWindow", "Set as Origin", None))
        self.groupBox_Navigator.setTitle(_translate("MainWindow", "Navigator", None))
        self.buttonYp.setToolTip(_translate("MainWindow", "Move along +Y", None))
        self.buttonXp.setToolTip(_translate("MainWindow", "Move along +X", None))
        self.buttonYn.setToolTip(_translate("MainWindow", "Move along -Y", None))
        self.buttonXn.setToolTip(_translate("MainWindow", "Move along -X", None))
        self.comboLive.setToolTip(_translate("MainWindow", "Select target well", None))
        self.buttonGo.setToolTip(_translate("MainWindow", "Go to target", None))
        self.buttonGo.setText(_translate("MainWindow", "Go", None))
        self.groupBox_CamParam.setTitle(_translate("MainWindow", "Camera Settings", None))
        self.label_3.setText(_translate("MainWindow", "Brightness", None))
        self.label_4.setText(_translate("MainWindow", "Contrast", None))
        self.label_5.setText(_translate("MainWindow", "Saturation", None))
        self.label_6.setText(_translate("MainWindow", "Exposure", None))
        self.label_11.setText(_translate("MainWindow", "Hue", None))
        self.label_12.setText(_translate("MainWindow", "Gain", None))
        self.label_13.setText(_translate("MainWindow", "Sharpness", None))
        self.buttonSnapshot.setText(_translate("MainWindow", "Get Snapshot", None))
        self.pushButton_7.setText(_translate("MainWindow", "S", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Live View", None))
        self.label_28.setText(_translate("MainWindow", "Folders:", None))
        self.pngViewer.setText(_translate("MainWindow", "No File Selected", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Parameters", None))
        self.label_33.setText(_translate("MainWindow", "Cycle :", None))
        self.label_29.setText(_translate("MainWindow", "Comp. Con.", None))
        self.label_34.setText(_translate("MainWindow", "Compound :", None))
        self.labelPNG_Cell.setText(_translate("MainWindow", "...", None))
        self.labelPNG_Well.setText(_translate("MainWindow", "...", None))
        self.label_31.setText(_translate("MainWindow", "Well:", None))
        self.labelPNG_Compund.setText(_translate("MainWindow", "...", None))
        self.label_32.setText(_translate("MainWindow", "Cell:", None))
        self.label_30.setText(_translate("MainWindow", "Wells:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analyzer", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Logger", None))

import Resource_CC_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

